name: deploy
on:
  pull_request:
    branches: [ dev,release]
    types: [ closed ]
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v2
      - name: created_delta
        run: |
          echo "Creating delta..."
          # Add your delta creation commands here
      - name: deploying
        run: |
          echo "Deploying to org..."
          # Add your sandbox deployment commands here
      - name: pushing_tag
        run: |
          echo "Pushing tag..."
          # Add your tag pushing commands here
          job_id=${{ github.run_id }}
          date=$(date +%Y-%m-%d)
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -a "$date-$job_id" -m "Deployment tag for job $job_id on $date"
          git push origin --tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
      
        